# Generated by Django 4.2.23 on 2025-06-29 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("video_processor", "0003_add_user_multitenancy"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="videojob",
            name="video_proce_user_id_1e37ca_idx",
        ),
        migrations.RemoveIndex(
            model_name="videojob",
            name="video_proce_user_id_8e6a8a_idx",
        ),
    ]
