# Generated by Django 4.2.23 on 2025-08-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "video_processor",
            "0004_remove_videojob_video_proce_user_id_1e37ca_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="videojob",
            name="video_name",
            field=models.CharField(help_text="Original video filename", max_length=500),
        ),
    ]
